/**
 * 詩文元資料配置
 *
 * 100首詩的已知詩題與作者對照表。
 * 此為靜態配置，用於輔助 PDF 解析時的校正。
 */

export interface PoemMeta {
  num: number;
  title: string;
  author: string;
}

export const POEM_META: readonly PoemMeta[] = [
  { num: 1, title: '垓下歌', author: '項羽' },
  { num: 2, title: '江南', author: '漢樂府' },
  { num: 3, title: '長歌行', author: '漢樂府' },
  { num: 4, title: '十五從軍征', author: '漢樂府' },
  { num: 5, title: '庭中有奇樹', author: '《古詩十九首》' },
  { num: 6, title: '短歌行', author: '曹操' },
  { num: 7, title: '七步詩', author: '曹植' },
  { num: 8, title: '歸園田居（其三）', author: '陶淵明' },
  { num: 9, title: '雜詩（其一）', author: '陶淵明' },
  { num: 10, title: '敕勒歌', author: '北朝民歌' },
  { num: 11, title: '木蘭詩', author: '北朝民歌' },
  { num: 12, title: '詠螢', author: '虞世南' },
  { num: 13, title: '詠鵝', author: '駱賓王' },
  { num: 14, title: '送杜少府之任蜀州', author: '王勃' },
  { num: 15, title: '詠柳', author: '賀知章' },
  { num: 16, title: '回鄉偶書', author: '賀知章' },
  { num: 17, title: '春江花月夜', author: '張若虛' },
  { num: 18, title: '涼州詞', author: '王翰' },
  { num: 19, title: '涼州詞', author: '王之渙' },
  { num: 20, title: '登鸛鵲樓', author: '王之渙' },
  { num: 21, title: '春曉', author: '孟浩然' },
  { num: 22, title: '九月九日憶山東兄弟', author: '王維' },
  { num: 23, title: '相思', author: '王維' },
  { num: 24, title: '送元二使安西', author: '王維' },
  { num: 25, title: '送別', author: '王維' },
  { num: 26, title: '山中送別', author: '王維' },
  { num: 27, title: '鹿柴', author: '王維' },
  { num: 28, title: '竹里館', author: '王維' },
  { num: 29, title: '閨怨', author: '王昌齡' },
  { num: 30, title: '出塞', author: '王昌齡' },
  { num: 31, title: '靜夜思', author: '李白' },
  { num: 32, title: '送友人', author: '李白' },
  { num: 33, title: '黃鶴樓送孟浩然之廣陵', author: '李白' },
  { num: 34, title: '望廬山瀑布', author: '李白' },
  { num: 35, title: '秋浦歌', author: '李白' },
  { num: 36, title: '獨坐敬亭山', author: '李白' },
  { num: 37, title: '贈汪倫', author: '李白' },
  { num: 38, title: '早發白帝城', author: '李白' },
  { num: 39, title: '黃鶴樓', author: '崔顥' },
  { num: 40, title: '兵車行', author: '杜甫' },
  { num: 41, title: '春望', author: '杜甫' },
  { num: 42, title: '客至', author: '杜甫' },
  { num: 43, title: '絕句', author: '杜甫' },
  { num: 44, title: '月夜', author: '杜甫' },
  { num: 45, title: '楓橋夜泊', author: '張繼' },
  { num: 46, title: '江村即事', author: '司空曙' },
  { num: 47, title: '滁州西澗', author: '韋應物' },
  { num: 48, title: '遊子吟', author: '孟郊' },
  { num: 49, title: '小松', author: '杜荀鶴' },
  { num: 50, title: '初春小雨', author: '韓愈' },
  { num: 51, title: '竹枝詞（其一）', author: '劉禹錫' },
  { num: 52, title: '烏衣巷', author: '劉禹錫' },
  { num: 53, title: '賦得古原草送別', author: '白居易' },
  { num: 54, title: '暮江吟', author: '白居易' },
  { num: 55, title: '問劉十九', author: '白居易' },
  { num: 56, title: '憫農（其二）', author: '李紳' },
  { num: 57, title: '江雪', author: '柳宗元' },
  { num: 58, title: '尋隱者不遇', author: '賈島' },
  { num: 59, title: '近試上張籍水部', author: '朱慶餘' },
  { num: 60, title: '金縷衣', author: '杜秋娘' },
  { num: 61, title: '贈別', author: '杜牧' },
  { num: 62, title: '泊秦淮', author: '杜牧' },
  { num: 63, title: '山行', author: '杜牧' },
  { num: 64, title: '清明', author: '杜牧' },
  { num: 65, title: '江南春', author: '杜牧' },
  { num: 66, title: '秋夕', author: '杜牧' },
  { num: 67, title: '登樂遊原', author: '李商隱' },
  { num: 68, title: '夜雨寄北', author: '李商隱' },
  { num: 69, title: '官倉鼠', author: '曹鄴' },
  { num: 70, title: '華山', author: '寇準' },
  { num: 71, title: '畫眉鳥', author: '歐陽修' },
  { num: 72, title: '淮中晚泊犢頭', author: '蘇舜欽' },
  { num: 73, title: '梅花', author: '王安石' },
  { num: 74, title: '元日', author: '王安石' },
  { num: 75, title: '登飛來峰', author: '王安石' },
  { num: 76, title: '泊船瓜洲', author: '王安石' },
  { num: 77, title: '書湖陰先生壁', author: '王安石' },
  { num: 78, title: '飲湖上初晴後雨', author: '蘇軾' },
  { num: 79, title: '題西林壁', author: '蘇軾' },
  { num: 80, title: '惠崇春江晚景', author: '蘇軾' },
  { num: 81, title: '花影', author: '蘇軾' },
  { num: 82, title: '贈劉景文', author: '蘇軾' },
  { num: 83, title: '病牛', author: '李綱' },
  { num: 84, title: '曉出淨慈寺送林子方', author: '楊萬里' },
  { num: 85, title: '小池', author: '楊萬里' },
  { num: 86, title: '宿新市徐公店', author: '楊萬里' },
  { num: 87, title: '觀書有感', author: '朱熹' },
  { num: 88, title: '春日', author: '朱熹' },
  { num: 89, title: '月兒彎彎照九州', author: '南宋民歌' },
  { num: 90, title: '題臨安邸', author: '林升' },
  { num: 91, title: '約客', author: '趙師秀' },
  { num: 92, title: '遊園不值', author: '葉紹翁' },
  { num: 93, title: '過零丁洋', author: '文天祥' },
  { num: 94, title: '墨梅（其三）', author: '王冕' },
  { num: 95, title: '素梅（其五十六）', author: '王冕' },
  { num: 96, title: '石灰吟', author: '于謙' },
  { num: 97, title: '畫雞', author: '唐寅' },
  { num: 98, title: '風鳶圖詩（其一）', author: '徐渭' },
  { num: 99, title: '竹石', author: '鄭燮' },
  { num: 100, title: '村居', author: '高鼎' },
] as const;

export const PDF_BASE_URL =
  'https://www.edb.gov.hk/attachment/tc/curriculum-development/kla/chi-edu/resources/primary/lang/jilei_shi_pdf/jilei_shi_{NUM:03d}.pdf';

export function getMeta(num: number): PoemMeta | undefined {
  return POEM_META.find((m) => m.num === num);
}
